### ISSUE TITLE
ERR_CONNECTION_REFUSED locally

### ISSUE THREAD

**Issue by padig** [dappblock/nextjs-ic-starter#15]
trying to run this locally and getting a net::ERR_CONNECTION_REFUSED 

I can see that NEXT_PUBLIC_IC_HOST=http://localhost:8000 is already set

I suspect this is something like a CORS issue, but a confirmation and resolution would be great

<img width="1352" alt="Screenshot 2023-09-13 at 8 23 47 PM" src="https://github.com/dappblock/nextjs-ic-starter/assets/5158168/22f1ce74-4d97-4a6f-8f42-17b5728d22ee">

**Comment by kinwo** [comment]
Hi @padig I just made a new release v0.5.0 for the latest DFX version 0.15. Please try it to see if the issue is resolved. https://github.com/dappblock/nextjs-ic-starter/releases/tag/0.5.0

Usually, "Unable to fetch root key" is caused by NextJS dev mode server side processing when it tries create canister actor.
The latest release v0.5.0 has addressed the issue by using node_compatibility in dfx canister declaration. See dfx.json.

Hope that helps.

**Comment by padig** [comment]
Thanks! Got it to work.
