### ISSUE TITLE
How to add now canister to backend

### ISSUE THREAD

**Issue by I-NI** [dappblock/nextjs-ic-starter#6]
Hi,

I am a green hand in ICP. I want to add a new motoko canister to backend. I meet an error : "Must specify a host to connect to"
![image](https://user-images.githubusercontent.com/22560100/157481785-31cbcc93-f57a-453d-b264-fac2a50ee98a.png)
For test, I add a Hello2.mo like this
![image](https://user-images.githubusercontent.com/22560100/157482271-64457fff-c8f6-4e40-ab6f-d35d51213d2c.png)
put it into the dfx.json
![image](https://user-images.githubusercontent.com/22560100/157482545-7296d1d0-977c-4e7c-aa5c-9b356a93a8c8.png)
then, I run "deploy hello2", it succeeds, and I copy interface declarations from .dfx/local/canisters/hello2 to /ui/declarations/hello2
![image](https://user-images.githubusercontent.com/22560100/157484048-f329448f-bc6b-4458-920b-31860d8de021.png)
next, I create a new actor in actor-locator.js, like this
![image](https://user-images.githubusercontent.com/22560100/157483205-c2ee874a-5d75-49b3-9ec1-93fb426a33ae.png)
finally, I use it in ui/components/GreetingSection.js like this
![image](https://user-images.githubusercontent.com/22560100/157483544-f85a8d7b-5fa6-4233-b12f-c6811f910c20.png)
I run dfx deploy and meet the error above.
What should I do to add a new backend? What steps did I miss? Need your help. Thanks

**Comment by kinwo** [comment]
Hey @I-NI ,  Great work trying to make a new Canister!  You are almost there.

## Solution
Check the generated UI declarations code you copied from .dfx/local/canisters/hello2 .

Open index.js

It should be similar to:
```
import { Actor, HttpAgent } from "@dfinity/agent";

// Imports and re-exports candid interface
import { idlFactory } from './hello2.did.js';
export { idlFactory } from './hello2.did.js';
// CANISTER_ID is replaced by webpack based on node environment
export const canisterId = process.env.NEXT_PUBLIC_HELLO2_CANISTER_ID;

/**
 * 
 * @param {string | import("@dfinity/principal").Principal} canisterId Canister ID of Agent
 * @param {{agentOptions?: import("@dfinity/agent").HttpAgentOptions; actorOptions?: import("@dfinity/agent").ActorConfig}} [options]
 * @return {import("@dfinity/agent").ActorSubclass<import("./hello2.did.js")._SERVICE>}
 */
 export const createActor = (canisterId, options) => {
  const agent = new HttpAgent({ ...options?.agentOptions });
  
  // Fetch root key for certificate validation during development
  if(process.env.NODE_ENV !== "production") {
    agent.fetchRootKey().catch(err=>{
      console.warn("Unable to fetch root key. Check to ensure that your local replica is running");
      console.error(err);
    });
  }

  // Creates an actor with using the candid interface and the HttpAgent
  return Actor.createActor(idlFactory, {
    agent,
    canisterId,
    ...options?.actorOptions,
  });
};
  
/**
 * A ready-to-use agent for the hello2 canister
 * @type {import("@dfinity/agent").ActorSubclass<import("./hello2.did.js")._SERVICE>}
 */
 export const hello2 = createActor(canisterId);
```

Remove the last line and its comments:

```
 export const hello2 = createActor(canisterId);
```

Also, make sure at the beginning, you have added prefix NEXT_PUBLIC_ to HELLO2_CANISTER_ID:

```
export const canisterId = process.env.NEXT_PUBLIC_HELLO2_CANISTER_ID;
```

Take a reference on https://github.com/dappblock/nextjs-ic-starter/blob/master/ui/declarations/hello/index.js.


## Explanation
That last line of code implicitly creates actor instance when it runs in NextJS on server side. Since it's a export const which means any file that import that will trigger create actor.

It couldn't find the host because NEXT_PUBLIC_IC_HOST is available to browser client-side processing only.
https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser

Remember Dfinity Agent JS code is supposed to run on client side only when you deploy it to Internet Computer Blockchain Asset Canister. The NextJS server side features won't work there.

If you see any Dfinity Agent error log thrown in NextJS command console e.g next dev or next start, your code is not pure client code.

Hope that helps.

**Comment by I-NI** [comment]
It works now! Thanks! @kinwo 

Anathor small question is that does ICP support multi page web app? which means deploying several  pages on a single canister, like
localhost:3000 and localhost:3000/starter
While, when I change to http://localhost:8000/starter?canisterId=[canisterId], it comes to the same page of index" even though the starter.html is in ./out.

Thanks a lot for your time!

**Comment by kinwo** [comment]
Hi @I-NI , nice ! Glad it works.

When you deploy the exported NextJS static pages to Internet Computer, they are all HTML and JavaScripts. That means 
you need to use starter.html.
[http://localhost:8000/starter.html?canisterId=[canisterId]](http://localhost:8000/starter.html?canisterId=%5BcanisterId%5D),

Cheers

**Comment by I-NI** [comment]
Thanks! @kinwo
